### ISSUE TITLE
HTML5 video support page linked to in sample code returns 404 not found

### ISSUE THREAD

**Issue by kevincon** [videojs/videojs.com#110]
The sample code provided on the Getting Started page for integrating VideoJS includes a link to https://videojs.com/html5-video-support/ for users who don't have JS enabled and/or are using a browser that does not support HTML5 video: https://videojs.com/getting-started

![image](https://user-images.githubusercontent.com/817753/69487736-e1949500-0e13-11ea-86e3-3d4b7cdbb24e.png)

Unfortunately, this link appears to return a 404 not found message on videojs.com when I try to access it via Chrome Version 78.0.3904.97 on Windows 10:

![image](https://user-images.githubusercontent.com/817753/69487751-202a4f80-0e14-11ea-82bb-eeaf107b8b90.png)

I discovered this because the CI for my personal website checks if any external links on my site are broken each week, and the build has been failing due to this issue: https://travis-ci.org/kevincon/kevintechnology.com/builds/615491436

**Comment by mmcc** [comment]
Oh yikes, ok we'll get this fixed ASAP, thanks for letting us know!

**Comment by kevincon** [comment]
Thank you for fixing it so quickly!
