### ISSUE TITLE
The "Getting Started" Link should point to the minified version

### ISSUE THREAD

**Issue by nathanchu** [videojs/videojs.com#124]
The code snippet at https://videojs.com/getting-started/#videojs-cdn uses https://vjs.zencdn.net/7.10.2/video.js as the videojs file. Why isn't the minifed version linked instead https://vjs.zencdn.net/7.10.2/video.min.js

**Comment by gkatsev** [comment]
Yeah, we probably should. Care to make a PR? While we're at it, remove the ie8 shim.
