### ISSUE TITLE
Double check on sites used

### ISSUE THREAD

**Issue by mmcc** [videojs/videojs.com#13]
Looks like Vine may have switched to using MediaElement's SWF instead of Video.js. Double check that (and others while we're at it).

**Comment by sprice** [comment]
Vine is gone from the list.

I checked a few of the ones currently on the list

### Instagram
* [Test URL](https://instagram.com/p/9uI2fPqu02/)
* `<video>` class is `-cx-PRIVATE-DeclarativeVideo__video`
* Seems not to use vjs

### Twitter
* [Test URL](https://twitter.com/twitter/status/560070183650213889)
* `<video>` class is `vjs-tech`
* Seems to use vjs

### Dropbox
* [Test URL](https://www.dropbox.com/s/os37b09t1bhz13f/Wildlife_512kb.mp4?dl=0)
* `<object>` class is `vjs-tech`
* Seems to use vjs

[Github doesn't play checked in videos](https://github.com/dailymotion/dailymotion-sdk-python/blob/master/examples/video.mp4), they may have training videos or such that uses video.js.

Did a quick search for Microsoft but nothing came up quickly. I'm sure someone else knows where to look for this.

**Comment by heff** [comment]
Logos got updated with the new site.
