### ISSUE TITLE
Small bug with checkboxes in the player controls 

### ISSUE THREAD

**Issue by minkyngkm** [videojs/videojs.com#161]
There seems to be a small bug with the checkboxes in the player controls.
Steps:
1. Go to http://videojs.com/
2. Scroll down to the "EXAMPLE Playlist plugin" section
![image](https://user-images.githubusercontent.com/57550290/192547828-a6fc1616-7f81-4a05-b126-5982d748647c.png)
3. Click checkbox labels in the player controls
When you click labels, they don't update checkboxes but a small dot is created above checkboxes.
![checkbox-before](https://user-images.githubusercontent.com/57550290/192536606-d4ac2164-0a97-43cb-a395-0bdb80b7690c.gif)

**Comment by gkatsev** [comment]
Fixed via #162
