### ISSUE TITLE
Update Twitter logo X

### ISSUE THREAD

**Issue by amanr-dev** [videojs/videojs.com#177]
### Description

Please update the Twitter logo to the latest version, as the current logo appears to be outdated.

### Reduced test case

https://videojs.com

### Steps to reproduce

Change the Twitter logo to X

### What version of Video.js are you using?

8.6.1

### What browser(s) including version(s) does this occur with?

Chrome

### What OS(es) and version(s) does this occur with?

Windows 11

**Comment by amanr-dev** [comment]
Hi, I updated the twitter logo in #178, please review the PR.

**Comment by heff** [comment]
Closed by #178
