### ISSUE TITLE
Add video.js documentation to the website

### ISSUE THREAD

**Issue by heff** [videojs/videojs.com#19]
Add video.js docs to the site so their more searchable and more integrated.

See videojs/video.js#2005 for the original issue.

> Their is a great Getting Started guide on the readme. Awesome.
> Their is a few guides for everything that we need on GitHub. Awesome.
> We don't need that much documentation. VJS is simple.
> 
> Where VJS fall short is on making that documentation a little bit easier to find and navigate. I think we could do a much better user experience if we had those same guides within videojs.com (mainly the navigation). We can generate them from the markdown files already in GitHub.
> 
> [fluxible](http://fluxible.io/quick-start.html) at Yahoo is doing an awesome job with that and maybe we could build something similar for VJS. Everything you see there is from a markdown file on GitHub.
> 
> Not a game changer but a nice-to-have that I'm sure a lot of people would love.

**Comment by mmcc** [comment]
bumping @exon since he opened this original one.

I have a big time crush on how Lodash does their documentation. Looks like he uses [docdown](https://github.com/jdalton/docdown), which supports JSDoc.
