### ISSUE TITLE
Create homepage player

### ISSUE THREAD

**Issue by mmcc** [videojs/videojs.com#21]
We want to do a sweet overlay on top of the player on the Videojs.com homepage. You can see the screenshot in #20, but that's pretty much the gist of it. You'll have access to Font Awesome icons for the Star + Twitter icons, and you can use the [videojs-overlay](https://github.com/brightcove/videojs-overlay) plugin to do it. I assume it should hide on play, show on pause, etc.

**Comment by dconnolly** [comment]
I'm going to start on this.

**Comment by sprice** [comment]
This seems to have been completed.
