### ISSUE TITLE
Adding plugin to http://videojs.com/plugins/

### ISSUE THREAD

**Issue by kmoskwiak** [videojs/videojs.com#33]
I've added to my `package.json` keyword `videojs-plugin` and published plugin on npm but it's not showing on new plugin page. Should I do something else?

**Comment by gkatsev** [comment]
Wait :)
Not sure exactly how it works, @mmcc will know better, but I believe it's on a cronjob right now and scraps npm every so often. Maybe soon we'll make it do it in closer to realtime.

**Comment by mmcc** [comment]
Just updated. I'm moving the plugin stuff to a lambda function to make it easier for everyone to administer, so I'll spread that knowledge amongst core team once it's ready. 

In the meantime, I'm going to have to do some manually updates. Woo. :confetti_ball:

**Comment by mmcc** [comment]
Updated to automatically scrape daily!
