### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by gkatsev** [videojs/videojs.com#44]
1. ~~Make PR against 5.0 branch~~
   1. [x] Make 5.0 branch master
2. ~~Merge PR into 5.0 branch~~
3. Make PR against `master` branch
4. Merge PR into `master`
5. Merge `master` branch into `gh-pages`
6. Run `grunt dist`
7. Run `git add -A`
8. Run `git commit -m "update dist"`
9. Run `git push origin gh-pages`

**Comment by ldayananda** [comment]
I believe this process is no longer needed?

**Comment by gkatsev** [comment]
correct.
