### ISSUE TITLE
Videojs website returns expired certificate

### ISSUE THREAD

**Issue by paladox** [videojs/videojs.com#62]
Hi when I go to https://videojs.com/ in Internet explorer, I get a red certificate and press continue to continue to site.

**Comment by paladox** [comment]
![screenshot 17](https://cloud.githubusercontent.com/assets/5727000/19253157/08040748-8f41-11e6-89ff-87e832e1e553.png)

**Comment by paladox** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/5727000/19253176/2c9d8912-8f41-11e6-9a7a-f14faf25d433.png)

**Comment by paladox** [comment]
![screenshot 5](https://cloud.githubusercontent.com/assets/5727000/19253189/3f484e80-8f41-11e6-9e1b-80374295a56f.png)

**Comment by gkatsev** [comment]
Yup, a known problem. Please use the http:// website for now.
It has to do with the fact that we're currently hosting it on gh-pages, so, getting SSL running for that is a bit tricky.

**Comment by paladox** [comment]
Oh, is there a way we could use letsencrypt?

**Comment by mmcc** [comment]
Not directly via GH Pages. The easiest route is going to be to just switch to something like [Netlify](http://netlify.com), otherwise we'll need something that can sit in front of GH Pages and fake SSL like Cloudflare.

**Comment by paladox** [comment]
Looks like https://www.netlify.com/pricing/ gives there free pro tier if your open source which videojs is.

**Comment by mister-ben** [comment]
Netlify seems a decent option.

**Comment by ldayananda** [comment]
I believe we're using Netlify now so this should be resolved. I'm going to close this issue.
