### ISSUE TITLE
who uses videojs?

### ISSUE THREAD

**Issue by thecotne** [videojs/videojs.com#77]
i am pretty sure many big companies use videojs 

but this list does not look correct

https://github.com/videojs/videojs.com/blob/master/_harp/_users.ejs

twitter video player is not videojs

<img width="1029" alt="screen shot 2018-02-19 at 01 22 16" src="https://user-images.githubusercontent.com/1606993/36357161-6078ef70-1513-11e8-9c1c-e22ad458483a.png">

this is from instagram (does not look like a videojs)

<img width="986" alt="screen shot 2018-02-19 at 01 24 45" src="https://user-images.githubusercontent.com/1606993/36357181-bbc53eba-1513-11e8-8cca-5e647e2f4999.png">

dropbox does use videojs

<img width="874" alt="screen shot 2018-02-19 at 01 30 52" src="https://user-images.githubusercontent.com/1606993/36357232-995b8c0c-1514-11e8-8718-0656cbcdee1b.png">

am i missing something or instagram and twitter are not using videojs?

**Comment by gkatsev** [comment]
Hi, thanks for the issue. Looks like we haven't updated that page in quite a long time (almost two years). At the time, those sites were definitely using Video.js but as time passed and needs and wants have changed, some have clearly moved to other video players. We definitely should update these. Also, ultimately, I'd like to make a page like [babel's users page](http://babeljs.io/users) where companies and projects can add themselves to.

**Comment by heff** [comment]
This is fixed as of the site update.
